const seedImageMap = {
  fedexo: '/uploads/images/catalog-fedexo.svg',
  fedin: '/uploads/images/catalog-fedin.svg',
  fedpour: '/uploads/images/catalog-fedpour.svg',
  spotex: '/uploads/images/catalog-spotex.svg',
};

const categories = [
  {
    id: 1,
    name: 'SPOTEX',
    slug: 'spotex',
    image: seedImageMap.spotex,
    description: 'SPOTEX are high density, highly exothermic sleeves designed for SPOT feeding. Our Feeding Systems are engineered to ensure optimal metal flow, solidification control, and defect-free castings. Designed with precision and backed by metallurgical expertise, our systems enhance yield, reduce shrinkage, and improve overall casting integrity.',
    sortOrder: 1,
  },
  {
    id: 2,
    name: 'FEDPOUR',
    slug: 'fedpour',
    image: seedImageMap.fedpour,
    description: 'FEDPOUR is a range of pouring solutions engineered for consistency and flow control',
    sortOrder: 2,
  },
  {
    id: 3,
    name: 'FEDEXO',
    slug: 'fedexo',
    image: seedImageMap.fedexo,
    description: 'FEDEXO is a range of high performance exothermic cum insulating sleeves built for precision applications and reliability',
    sortOrder: 3,
  },
  {
    id: 4,
    name: 'FEDIN',
    slug: 'fedin',
    image: seedImageMap.fedin,
    description: 'FEDIN are a range of insulating sleeves designed for consistency and durability',
    sortOrder: 4,
  },
];

const subCategories = [
  {
    id: 101,
    categoryId: 3,
    name: 'FEDEXO 55 (XP)',
    slug: 'fedexo-55-xp',
    image: seedImageMap.fedexo,
    description: 'FEDEXO 55 XP are exothermic and insulating sleeves available in a variety of shapes for most practical solutions for foundries.',
    sortOrder: 1,
  },
  {
    id: 102,
    categoryId: 3,
    name: 'FEDEXO 50',
    slug: 'fedexo-50',
    image: seedImageMap.fedexo,
    description: 'FEDEXO 50 – Exothermic and Insulating sleeves available from Ø 150 onwards.',
    sortOrder: 2,
  },
  {
    id: 103,
    categoryId: 3,
    name: 'FEDEXO LID',
    slug: 'fedexo-lid',
    image: seedImageMap.fedexo,
    description: 'FEDEXO LID – represents innovation, reliability, and precision in every solution we deliver.',
    sortOrder: 3,
  },
];

const products = [
  {
    id: 1001,
    categoryId: 3,
    subCategoryId: 101,
    name: 'EXOTHERMIC OPEN SLEEVES CYLINDRICAL',
    slug: 'exothermic-open-sleeves-cylindrical',
    shortDescription: 'Cylindrical open sleeves for open risers.',
    description: 'Highly Exothermic Open Sleeves – Cylindrical Type are for use as open risers. The sleeves can also be stacked to increase the height. Open sleeves should be used along with ISOTOP 041 (APC) for best results as per the datasheet.',
    thumbnail: seedImageMap.fedexo,
    gallery: [seedImageMap.fedexo],
    features: [
      {
        title: 'Cylindrical Shape',
        description: 'Designed for open riser systems; easy to position',
      },
      {
        title: 'Highly Exothermic',
        description: 'Generates intense heat upon metal contact, delaying solidification in the feeder and thus; Increases feeding efficiency',
      },
      {
        title: 'Sizes',
        description: 'Available 30mm to 225mm',
      },
    ],
    benefits: [
      'Increases the solidification time by 2 to 2.6 times depending on the size.',
      'Enhances yield.',
      'Consistency in casting quality.',
      'Cuts down on fettling time',
    ],
    specifications: {
      sizes: ['30mm', '50mm', '75mm', '100mm', '225mm'],
      material: 'Exothermic sleeve material',
      application: 'Open riser systems',
    },
    relatedProducts: [1002, 1003, 1006, 1007],
    sortOrder: 1,
  },
  {
    id: 1002,
    categoryId: 3,
    subCategoryId: 101,
    name: 'EXOTHERMIC BLIND SLEEVES CYLINDRICAL',
    slug: 'exothermic-blind-sleeves-cylindrical',
    shortDescription: 'High exothermic blind sleeves in cylindrical form.',
    description: 'Blind cylindrical sleeves designed to retain heat and support sound feeding in demanding castings.',
    thumbnail: seedImageMap.fedexo,
    gallery: [seedImageMap.fedexo],
    features: [
      {
        title: 'Blind End Geometry',
        description: 'Supports concentrated feeder heat retention for controlled solidification.',
      },
      {
        title: 'Cylindrical Design',
        description: 'Fits standard foundry feeder layouts with consistent positioning.',
      },
      {
        title: 'Exothermic Performance',
        description: 'Helps maintain feeder efficiency over extended solidification windows.',
      },
    ],
    benefits: [
      'Supports improved feeding performance.',
      'Enhances yield consistency.',
      'Reduces rework in critical casting zones.',
    ],
    specifications: {
      material: 'Exothermic sleeve material',
      application: 'Blind riser systems',
    },
    relatedProducts: [1001],
    sortOrder: 2,
  },
  {
    id: 1003,
    categoryId: 3,
    subCategoryId: 101,
    name: 'EXOTHERMIC NECK DOWN SLEEVES',
    slug: 'exothermic-neck-down-sleeves',
    shortDescription: 'High exothermic neck down sleeves.',
    description: 'Neck down sleeves engineered to direct feed metal efficiently into constrained sections.',
    thumbnail: seedImageMap.fedexo,
    gallery: [seedImageMap.fedexo],
    features: [
      {
        title: 'Reduced Neck Section',
        description: 'Improves feeding focus toward the casting hot spot.',
      },
      {
        title: 'Thermal Efficiency',
        description: 'Designed to retain heat while limiting excess feeder volume.',
      },
    ],
    benefits: [
      'Improves directional solidification.',
      'Helps optimise feeder-to-casting yield.',
    ],
    specifications: {
      material: 'Exothermic sleeve material',
      application: 'Constrained feeder neck applications',
    },
    relatedProducts: [1001, 1002],
    sortOrder: 3,
  },
  {
    id: 1006,
    categoryId: 3,
    subCategoryId: 101,
    name: 'EXOTHERMIC OVAL NECK DOWN SLEEVES',
    slug: 'exothermic-oval-neck-down-sleeves',
    shortDescription: 'Oval neck down sleeves for compact feeder layouts.',
    description: 'Oval neck down sleeves provide thermal support where feeder footprint and geometry are constrained.',
    thumbnail: seedImageMap.fedexo,
    gallery: [seedImageMap.fedexo],
    features: [
      {
        title: 'Oval Profile',
        description: 'Fits applications requiring non-circular feeder geometry.',
      },
      {
        title: 'Neck Down Feeding',
        description: 'Maintains focused feed performance into the casting section.',
      },
    ],
    benefits: [
      'Supports layout flexibility.',
      'Maintains strong feeding performance in limited space.',
    ],
    specifications: {
      material: 'Exothermic sleeve material',
      application: 'Oval neck down riser systems',
    },
    relatedProducts: [1001, 1003],
    sortOrder: 4,
  },
  {
    id: 1007,
    categoryId: 3,
    subCategoryId: 101,
    name: 'EXOTHERMIC OVAL OPEN SLEEVES',
    slug: 'exothermic-oval-open-sleeves',
    shortDescription: 'Exothermic and Insulating Oval Open Sleeves.',
    description: 'Oval open sleeves combine exothermic efficiency with a compact footprint for practical feeder placement.',
    thumbnail: seedImageMap.fedexo,
    gallery: [seedImageMap.fedexo],
    features: [
      {
        title: 'Open Riser Design',
        description: 'Supports open riser placement in oval feeder layouts.',
      },
      {
        title: 'Exothermic Support',
        description: 'Retains heat for improved feeding duration.',
      },
    ],
    benefits: [
      'Supports stable feeder performance.',
      'Helps reduce shrinkage-related defects.',
    ],
    specifications: {
      material: 'Exothermic sleeve material',
      application: 'Open oval riser systems',
    },
    relatedProducts: [1001, 1006],
    sortOrder: 5,
  },
  {
    id: 1004,
    categoryId: 3,
    subCategoryId: 102,
    name: 'FEDEXO 50 STANDARD SLEEVES',
    slug: 'fedexo-50-standard-sleeves',
    shortDescription: 'Exothermic and insulating sleeves with stable and repeatable performance.',
    description: 'FEDEXO 50 standard sleeves provide balanced thermal support for everyday foundry feeding applications.',
    thumbnail: seedImageMap.fedexo,
    gallery: [seedImageMap.fedexo],
    features: [
      {
        title: 'Balanced Insulation',
        description: 'Combines exothermic and insulating behaviour for dependable feeding.',
      },
    ],
    benefits: ['Enhances yield.', 'Improves consistency.'],
    specifications: {
      application: 'General feeder systems',
    },
    relatedProducts: [1001],
    sortOrder: 6,
  },
  {
    id: 1005,
    categoryId: 3,
    subCategoryId: 103,
    name: 'FEDEXO LID',
    slug: 'fedexo-lid-product',
    shortDescription: 'Innovative precision feeding solution.',
    description: 'FEDEXO LID improves thermal control for difficult feed zones.',
    thumbnail: seedImageMap.fedexo,
    gallery: [seedImageMap.fedexo],
    features: [
      {
        title: 'Lid-Based Control',
        description: 'Improves thermal management in complex feeder configurations.',
      },
    ],
    benefits: ['Improves feed control.', 'Supports better casting quality.'],
    specifications: {
      application: 'Precision feeding zones',
    },
    relatedProducts: [1001],
    sortOrder: 7,
  },
  {
    id: 2001,
    categoryId: 3,
    subCategoryId: null,
    name: 'BREAKER CORE',
    slug: 'breaker-core',
    shortDescription: 'Breaker core product.',
    description: 'Breaker core used for casting applications.',
    thumbnail: seedImageMap.fedexo,
    gallery: [seedImageMap.fedexo],
    features: [],
    benefits: [],
    specifications: {},
    relatedProducts: [],
    sortOrder: 6,
  },
  {
    id: 3001,
    categoryId: 1,
    subCategoryId: null,
    name: 'SPOTEX HD V-SERIES',
    slug: 'spotex-hd-v-series',
    shortDescription: 'SPOTEX HD V-Series – High density Sleeves. Spotex HD V-Series is the high-density range of exothermic sleeves.',
    description: 'SPOTEX V-Series is the high density range of exothermic sleeves. These systems are engineered to ensure optimal metal flow, solidification control and defect-free castings.',
    thumbnail: seedImageMap.spotex,
    gallery: [seedImageMap.spotex],
    features: [
      {
        title: 'High Performance Cover Material Sleeve',
        description: 'Designed to deliver reliable feeding performance in demanding castings.',
      },
      {
        title: 'Low Thermal Loss in Mould Sand',
        description: 'Maintains effective heat retention for longer feeder action.',
      },
      {
        title: 'Reduction in Fettling due to the Neck Size',
        description: 'Helps reduce downstream cleanup effort after casting.',
      },
      {
        title: 'Flexibility to Use Directly or with Feeder Core',
        description: 'Supports multiple foundry process preferences.',
      },
    ],
    benefits: [
      'Improves mould feeding efficiency.',
      'Higher exothermic output.',
      'Higher stiffness due to reduced fettling time.',
      'Directly fit due to the existing sleeve and mould compatibility.',
    ],
    specifications: {
      application: 'Spot feeding',
      material: 'High density exothermic sleeve material',
    },
    relatedProducts: [3002],
    sortOrder: 1,
  },
  {
    id: 3002,
    categoryId: 1,
    subCategoryId: null,
    name: 'SPOTEX HD VC-SERIES',
    slug: 'spotex-hd-vc-series',
    shortDescription: 'Spotex HD VC-Series - High-density Sleeves. Spotex HD VC-Series is the high-density range of exothermic sleeves.',
    description: 'SPOTEX HD VC-Series from INEXO is the high density range of exothermic sleeves developed for consistent feeding and improved casting integrity.',
    thumbnail: seedImageMap.spotex,
    gallery: [seedImageMap.spotex],
    features: [
      {
        title: 'Consistent Thermal Support',
        description: 'Maintains dependable feeding performance across repeated foundry cycles.',
      },
      {
        title: 'High Density Sleeve Construction',
        description: 'Supports better feeder action and casting soundness.',
      },
    ],
    benefits: [
      'Supports reliable foundry output.',
      'Helps improve casting quality.',
    ],
    specifications: {
      application: 'Spot feeding',
      material: 'High density exothermic sleeve material',
    },
    relatedProducts: [3001],
    sortOrder: 2,
  },
  {
    id: 4001,
    categoryId: 2,
    subCategoryId: null,
    name: 'FEDPOUR RT',
    slug: 'fedpour-rt',
    shortDescription: 'Pouring solution for repeatable process performance.',
    description: 'FEDPOUR RT products are designed for stable and controlled pouring behavior.',
    thumbnail: seedImageMap.fedpour,
    gallery: [seedImageMap.fedpour],
    features: [],
    benefits: ['Supports smooth mold filling.', 'Improves repeatability.'],
    specifications: {},
    relatedProducts: [],
    sortOrder: 1,
  },
  {
    id: 5001,
    categoryId: 4,
    subCategoryId: null,
    name: 'FEDIN INSUL',
    slug: 'fedin-insul',
    shortDescription: 'Insulating sleeve range for durable process windows.',
    description: 'FEDIN INSUL helps maintain stable casting conditions across repeated runs.',
    thumbnail: seedImageMap.fedin,
    gallery: [seedImageMap.fedin],
    features: [],
    benefits: ['Stable insulation.', 'Consistent quality output.'],
    specifications: {},
    relatedProducts: [],
    sortOrder: 1,
  },
  {
    id: 6001,
    categoryId: null,
    subCategoryId: null,
    name: 'STANDALONE PRODUCT',
    slug: 'standalone-product',
    shortDescription: 'Product without category.',
    description: 'Direct standalone product page.',
    thumbnail: seedImageMap.spotex,
    gallery: [seedImageMap.spotex],
    features: [],
    benefits: [],
    specifications: {},
    relatedProducts: [],
    sortOrder: 1,
  },
  {
    id: 6002,
    categoryId: null,
    subCategoryId: null,
    name: 'CORE PASTE - 05',
    slug: 'core-paste-05',
    shortDescription: 'Core Paste - 05',
    description: 'Core Paste - 05',
    thumbnail: seedImageMap.spotex,
    gallery: [seedImageMap.spotex],
    features: [],
    benefits: [],
    specifications: {},
    relatedProducts: [],
    sortOrder: 9,
  },
];

module.exports = {
  categories,
  products,
  seedImageMap,
  subCategories,
};